In [1]:
pip install python-dotenv

Requirement already satisfied: python-dotenv in c:\users\mohamed\appdata\local\programs\python\python310\lib\site-packages (1.2.1)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 26.1.2 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [21]:
import os
from dotenv import load_dotenv

load_dotenv()

api_key = os.getenv("MY_API_KEY")
Server = os.getenv("DB_SERVER")
username = os.getenv("DB_USERNAME")
password = os.getenv("DB_PASSWORD")

In [4]:
cities = [
    "Cairo",
    "Giza",
    "Alexandria",
    "Port Said",
    "Suez",
    "Ismailia",
    "Mansoura",
    "Tanta",
    "Luxor",
    "Aswan"
]

In [5]:
import requests
url = "https://api.openweathermap.org/data/2.5/weather"

c:\Users\mohamed\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\__init__.py:113: RequestsDependencyWarning: urllib3 (2.6.3) or chardet (7.4.3)/charset_normalizer (3.4.4) doesn't match a supported version!
  warnings.warn(

In [6]:
info=[]
for city in cities:
    params = {
    "appid": api_key,
    "q": f'{city}'
    }

    response = requests.get(url, params=params)
    data = response.json()
    data
    info.append(
        {
    'country':'Egypt',
    'city':f'{city}',
    'Longitude':data['coord']['lon'],
    'Latitude':data['coord']['lat'],
    'temprature':data['main']['temp'],
    'humidity':data['main']['humidity'],
    'pressure':data['main']['pressure']
    })

In [7]:
import pandas as pd
df = pd.DataFrame(info)
df

  country        city  Longitude  Latitude  temprature  humidity  pressure
0   Egypt       Cairo    31.2497   30.0626      300.57        61      1017
1   Egypt        Giza    31.2109   30.0081      300.56        57      1017
2   Egypt  Alexandria    29.9553   31.2156      298.13        73      1017
3   Egypt   Port Said    32.2841   31.2565      299.14        69      1017
4   Egypt        Suez    32.5263   29.9737      298.93        64      1017
5   Egypt    Ismailia    32.2723   30.6043      298.86        71      1017
6   Egypt    Mansoura    -1.3394   34.8616      291.94        78      1021
7   Egypt       Tanta    31.0019   30.7885      298.95        69      1017
8   Egypt       Luxor    32.6421   25.6989      304.18        35      1014
9   Egypt       Aswan    32.9070   24.0934      306.76        24      1013

Transformaiton

In [8]:
df['temp_in_cel']=df['temprature']-273

In [9]:
df

,country,city,Longitude,Latitude,temprature,humidity,pressure,temp_in_cel
0,Egypt,Cairo,31.2497,30.0626,300.57,61,1017,27.57
1,Egypt,Giza,31.2109,30.0081,300.56,57,1017,27.56
2,Egypt,Alexandria,29.9553,31.2156,298.13,73,1017,25.13
3,Egypt,Port Said,32.2841,31.2565,299.14,69,1017,26.14
4,Egypt,Suez,32.5263,29.9737,298.93,64,1017,25.93
5,Egypt,Ismailia,32.2723,30.6043,298.86,71,1017,25.86
6,Egypt,Mansoura,-1.3394,34.8616,291.94,78,1021,18.94
7,Egypt,Tanta,31.0019,30.7885,298.95,69,1017,25.95
8,Egypt,Luxor,32.6421,25.6989,304.18,35,1014,31.18
9,Egypt,Aswan,32.9070,24.0934,306.76,24,1013,33.76

In [ ]:
  * Greater Cairo
  * North Coast
  * Lower Egypt
  * Upper Egypt
  * Canal
  * Sinai
  * Red Sea

In [10]:
def func1(city):
    if city=='Cairo':
        return 'Greater Cairo'
    elif city=='Giza':
        return 'Greater Cairo'
    elif city=='Alexandria':
        return 'Lower Egypt'
    elif city== 'Port Said':
        return 'Canal'
    elif city== 'Suez':
        return 'Canal'
    elif city== 'Ismailia':
            return 'Sinai'
    elif city== 'Mansoura':
                return 'Sinai'
    elif city== 'Tanta':
                return 'Red Sea'
    elif city== 'Luxor':
                return 'Upper Egypt'
    elif city== 'Aswan':
                    return 'Upper Egypt'

In [11]:
df['region']=df['city'].apply(func1)

In [12]:
df

,country,city,Longitude,Latitude,temprature,humidity,pressure,temp_in_cel,region
0,Egypt,Cairo,31.2497,30.0626,300.57,61,1017,27.57,Greater Cairo
1,Egypt,Giza,31.2109,30.0081,300.56,57,1017,27.56,Greater Cairo
2,Egypt,Alexandria,29.9553,31.2156,298.13,73,1017,25.13,Lower Egypt
3,Egypt,Port Said,32.2841,31.2565,299.14,69,1017,26.14,Canal
4,Egypt,Suez,32.5263,29.9737,298.93,64,1017,25.93,Canal
5,Egypt,Ismailia,32.2723,30.6043,298.86,71,1017,25.86,Sinai
6,Egypt,Mansoura,-1.3394,34.8616,291.94,78,1021,18.94,Sinai
7,Egypt,Tanta,31.0019,30.7885,298.95,69,1017,25.95,Red Sea
8,Egypt,Luxor,32.6421,25.6989,304.18,35,1014,31.18,Upper Egypt
9,Egypt,Aswan,32.9070,24.0934,306.76,24,1013,33.76,Upper Egypt

In [13]:
df['TemperatureCategory']=df['temp_in_cel'].apply(lambda x : 'hot' if x >=30 else 'cold' )

In [14]:
df

,country,city,Longitude,Latitude,temprature,humidity,pressure,temp_in_cel,region,TemperatureCategory
0,Egypt,Cairo,31.2497,30.0626,300.57,61,1017,27.57,Greater Cairo,cold
1,Egypt,Giza,31.2109,30.0081,300.56,57,1017,27.56,Greater Cairo,cold
2,Egypt,Alexandria,29.9553,31.2156,298.13,73,1017,25.13,Lower Egypt,cold
3,Egypt,Port Said,32.2841,31.2565,299.14,69,1017,26.14,Canal,cold
4,Egypt,Suez,32.5263,29.9737,298.93,64,1017,25.93,Canal,cold
5,Egypt,Ismailia,32.2723,30.6043,298.86,71,1017,25.86,Sinai,cold
6,Egypt,Mansoura,-1.3394,34.8616,291.94,78,1021,18.94,Sinai,cold
7,Egypt,Tanta,31.0019,30.7885,298.95,69,1017,25.95,Red Sea,cold
8,Egypt,Luxor,32.6421,25.6989,304.18,35,1014,31.18,Upper Egypt,hot
9,Egypt,Aswan,32.9070,24.0934,306.76,24,1013,33.76,Upper Egypt,hot

In [15]:
df['humidityCategory']=df['humidity'].apply(lambda x : 'high' if x >=30 else 'low' )

In [16]:
import datetime
df['IngestionTime'] = datetime.datetime.now()

In [17]:
df

,country,city,Longitude,Latitude,temprature,humidity,pressure,temp_in_cel,region,TemperatureCategory,humidityCategory,IngestionTime
0,Egypt,Cairo,31.2497,30.0626,300.57,61,1017,27.57,Greater Cairo,cold,high,2026-09-23 22:41:30.569807
1,Egypt,Giza,31.2109,30.0081,300.56,57,1017,27.56,Greater Cairo,cold,high,2026-09-23 22:41:30.569807
2,Egypt,Alexandria,29.9553,31.2156,298.13,73,1017,25.13,Lower Egypt,cold,high,2026-09-23 22:41:30.569807
3,Egypt,Port Said,32.2841,31.2565,299.14,69,1017,26.14,Canal,cold,high,2026-09-23 22:41:30.569807
4,Egypt,Suez,32.5263,29.9737,298.93,64,1017,25.93,Canal,cold,high,2026-09-23 22:41:30.569807
5,Egypt,Ismailia,32.2723,30.6043,298.86,71,1017,25.86,Sinai,cold,high,2026-09-23 22:41:30.569807
6,Egypt,Mansoura,-1.3394,34.8616,291.94,78,1021,18.94,Sinai,cold,high,2026-09-23 22:41:30.569807
7,Egypt,Tanta,31.0019,30.7885,298.95,69,1017,25.95,Red Sea,cold,high,2026-09-23 22:41:30.569807
8,Egypt,Luxor,32.6421,25.6989,304.18,35,1014,31.18,Upper Egypt,hot,high,2026-09-23 22:41:30.569807
9,Egypt,Aswan,32.9070,24.0934,306.76,24,1013,33.76,Upper Egypt,hot,low,2026-09-23 22:41:30.569807

In [18]:
df.drop('temprature', axis=1 , inplace=True)

In [19]:
df['IngestionTime']=datetime.datetime.now().strftime('%Y-%m-%d %I:%M %p')

In [20]:
df

,country,city,Longitude,Latitude,humidity,pressure,temp_in_cel,region,TemperatureCategory,humidityCategory,IngestionTime
0,Egypt,Cairo,31.2497,30.0626,61,1017,27.57,Greater Cairo,cold,high,2026-09-23 10:41 PM
1,Egypt,Giza,31.2109,30.0081,57,1017,27.56,Greater Cairo,cold,high,2026-09-23 10:41 PM
2,Egypt,Alexandria,29.9553,31.2156,73,1017,25.13,Lower Egypt,cold,high,2026-09-23 10:41 PM
3,Egypt,Port Said,32.2841,31.2565,69,1017,26.14,Canal,cold,high,2026-09-23 10:41 PM
4,Egypt,Suez,32.5263,29.9737,64,1017,25.93,Canal,cold,high,2026-09-23 10:41 PM
5,Egypt,Ismailia,32.2723,30.6043,71,1017,25.86,Sinai,cold,high,2026-09-23 10:41 PM
6,Egypt,Mansoura,-1.3394,34.8616,78,1021,18.94,Sinai,cold,high,2026-09-23 10:41 PM
7,Egypt,Tanta,31.0019,30.7885,69,1017,25.95,Red Sea,cold,high,2026-09-23 10:41 PM
8,Egypt,Luxor,32.6421,25.6989,35,1014,31.18,Upper Egypt,hot,high,2026-09-23 10:41 PM
9,Egypt,Aswan,32.9070,24.0934,24,1013,33.76,Upper Egypt,hot,low,2026-09-23 10:41 PM

In [129]:
df.drop('IngestionTime', axis=1 , inplace=True)

In [141]:
df

,country,city,Longitude,Latitude,humidity,pressure,temp_in_cel,region,TemperatureCategory,humidityCategory,IngestionTime
0,Egypt,Cairo,31.2497,30.0626,35,1015,30.57,Greater Cairo,hot,high,2026-09-19 07:05 PM
1,Egypt,Giza,31.2109,30.0081,33,1015,30.56,Greater Cairo,hot,high,2026-09-19 07:05 PM
2,Egypt,Alexandria,29.9553,31.2156,54,1017,28.13,Lower Egypt,cold,high,2026-09-19 07:05 PM
3,Egypt,Port Said,32.2841,31.2565,54,1016,28.14,Canal,cold,high,2026-09-19 07:05 PM
4,Egypt,Suez,32.5263,29.9737,32,1015,31.18,Canal,hot,high,2026-09-19 07:05 PM
5,Egypt,Ismailia,32.2723,30.6043,45,1015,32.19,Sinai,hot,high,2026-09-19 07:05 PM
6,Egypt,Mansoura,-1.3394,34.8616,48,1016,24.94,Sinai,cold,high,2026-09-19 07:05 PM
7,Egypt,Tanta,31.0019,30.7885,34,1015,30.90,Red Sea,hot,high,2026-09-19 07:05 PM
8,Egypt,Luxor,32.6421,25.6989,17,1010,38.18,Upper Egypt,hot,low,2026-09-19 07:05 PM
9,Egypt,Aswan,32.9070,24.0934,14,1011,40.76,Upper Egypt,hot,low,2026-09-19 07:05 PM

loading

In [22]:
import pyodbc
conn=pyodbc.connect(
    "DRIVER={ODBC Driver 17 for SQL Server};"
    "SERVER=" + Server + ";"
    "DATABASE=Depi;"
    "UID=" + username + ";"
    "PWD=" + password + ";"
)
cursor=conn.cursor()

OperationalError: ('08001', '[08001] [Microsoft][ODBC Driver 17 for SQL Server]TCP Provider: Timeout error [258].  (258) (SQLDriverConnect); [08001] [Microsoft][ODBC Driver 17 for SQL Server]Login timeout expired (0); [08001] [Microsoft][ODBC Driver 17 for SQL Server]Unable to complete login process due to delay in login response (258)')

In [99]:
cursor.commit()
cursor.close()

In [142]:
output= list(df.itertuples(index=None, name=None))
output

[('Egypt',
  'Cairo',
  31.2497,
  30.0626,
  35,
  1015,
  30.569999999999993,
  'Greater Cairo',
  'hot',
  'high',
  '2026-09-19 07:05 PM'),
 ('Egypt',
  'Giza',
  31.2109,
  30.0081,
  33,
  1015,
  30.560000000000002,
  'Greater Cairo',
  'hot',
  'high',
  '2026-09-19 07:05 PM'),
 ('Egypt',
  'Alexandria',
  29.9553,
  31.2156,
  54,
  1017,
  28.129999999999995,
  'Lower Egypt',
  'cold',
  'high',
  '2026-09-19 07:05 PM'),
 ('Egypt',
  'Port Said',
  32.2841,
  31.2565,
  54,
  1016,
  28.139999999999986,
  'Canal',
  'cold',
  'high',
  '2026-09-19 07:05 PM'),
 ('Egypt',
  'Suez',
  32.5263,
  29.9737,
  32,
  1015,
  31.180000000000007,
  'Canal',
  'hot',
  'high',
  '2026-09-19 07:05 PM'),
 ('Egypt',
  'Ismailia',
  32.2723,
  30.6043,
  45,
  1015,
  32.19,
  'Sinai',
  'hot',
  'high',
  '2026-09-19 07:05 PM'),
 ('Egypt',
  'Mansoura',
  -1.3394,
  34.8616,
  48,
  1016,
  24.939999999999998,
  'Sinai',
  'cold',
  'high',
  '2026-09-19 07:05 PM'),
 ('Egypt',
  'Tanta',
  31.0019,
  30.7885,
  34,
  1015,
  30.899999999999977,
  'Red Sea',
  'hot',
  'high',
  '2026-09-19 07:05 PM'),
 ('Egypt',
  'Luxor',
  32.6421,
  25.6989,
  17,
  1010,
  38.18000000000001,
  'Upper Egypt',
  'hot',
  'low',
  '2026-09-19 07:05 PM'),
 ('Egypt',
  'Aswan',
  32.907,
  24.0934,
  14,
  1011,
  40.75999999999999,
  'Upper Egypt',
  'hot',
  'low',
  '2026-09-19 07:05 PM')]

In [157]:
cursor.execute('''create table mohamed_Ramadan2
( country varchar(50),
city varchar(50),
Longitude varchar(50) ,
Latitude varchar(50) ,
humidity varchar(50) ,
pressure varchar(50),
temp_in_cel varchar(50),
region varchar(50),
TemperatureCategory varchar(50) , 
humidityCategory varchar(50),
IngestionTime varchar(50) )''')

ProgrammingError: Attempt to use a closed cursor.

In [159]:
cursor.execute('''drop table mohamed_Ramadan''')

In [ ]:
sql="""  
insert into mohamed_Ramadan2  values (?,?,?,?,?,?,?,?,?,?,?)
""" 
cursor.executemany(sql,output)

In [161]:

cursor.commit()
cursor.close()

ProgrammingError: Attempt to use a closed cursor.